function [forward_map, reverse_map] = get_quality_metric_map
    metric_names = { 'T_maxval', 'T_corruption', 'T_max_corr', ...
        'S_area_1', 'S_smooth_area_1', 'S_area_2', 'S_smooth_area_2', 'S_max_corr', ...
        'S_corruption', 'S_eccent', 'S_circularity',...
        'ST1_index_1', 'ST1_index_2', 'ST1_index_3', 'ST1_index_4',...
        'ST1_index_5', 'ST2_index_1', 'ST2_index_2', 'ST2_index_3',...
        'ST2_index_4', 'ST2_index_5', 'ST3_index_1', 'ST3_index_2',...
        'ST3_index_3', 'ST3_index_4', 'ST3_index_5', 'ST_corr_1', ...
        'ST_corr_2', 'ST_corr_3'};
    metric_indices = 1:length(metric_names);
    forward_map = containers.Map(metric_names, metric_indices);
    reverse_map = containers.Map(metric_indices, metric_names);
end